import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier/flat'

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Must stay last: turns off the stylistic rules that would otherwise fight
  // with Prettier. Previously the package was installed but never wired up.
  prettier,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by vitest coverage
    'coverage/**',
    // Generated by prisma
    'src/generated/**',
    // Vendored agent skill packs — not application code
    '.agents/**',
    '.claude/**',
    '.windsurf/**',
    // Standalone CommonJS utility script at the repo root, not part of the
    // application. It predates this config and uses require() by design.
    'collect.js',
    // Its output.
    'output.txt',
  ]),
])

export default eslintConfig
